dado = input('Digite algo: ')

print('O tipo primitivo desse dado é: {}'.format(type(dado)))
print('Só tem espaços? {}'.format(dado.isspace()))
print('É alfanumérico? {}'.format(dado.isalnum()))
print('É um dígito? {}'.format(dado.isdigit()))
print('É um caractere ASCII? {}'.format(dado.isascii()))
print('É minúsculo? {}'.format(dado.islower()))
print('É decimal? {}'.format(dado.isdecimal()))
print('É numérico? {}'.format(dado.isnumeric()))
print('É printável? {}'.format(dado.isprintable()))
print('É maiúsculo? {}'.format(dado.isupper()))
print('É alfabético? {}'.format(dado.isalpha()))
print('Está capitalizada? {}'.format(dado.istitle()))